name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4

      - name: NPM install cache
        uses: c-hive/gha-npm-cache@v1

      - name: Install Node dependencies
        run: npm install

      - name: Run Test
        run: |
          npm test
          npm run coverage
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/
