name: Setup

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn

    - name: Install dependencies
      shell: bash
      run: yarn --prefer-offline
