#Included:
#                 1. Install and Download Dependencies
#                 2. Compile Contracts
#                 3. Deploy a Contract to the Local network
#                 4. Test the locally deployed Contract in the local network.
#                 5. Run all tests
#                 6. slither integration

name: ci-checks

on: [push]

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-and-deploy-contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile & Build Contracts
        run: yarn compile
      - name: Deploy Contracts Locally
        run: yarn deploy
        id: deployment-successful

      # - name: Interact With Contracts
      #   run: yarn interact

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Set up environment
      # uses: ./.github/actions/setup
      - name: Lint Contracts
        run: yarn lint:contracts
        continue-on-error: true

  tests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      # - name: Wait for compilation to succeed
      - uses: actions/checkout@v3
      - name: Compile contracts
        run: yarn compile
      # - name: Wait for tests to succeed
      #   uses: lewagon/wait-on-check-action@v1.0.0
      #   with:
      #     ref: master
      #     check-name: test
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     wait-interval: 25

      # - name: Set up environment
      #   uses: ./.github/actions/setup
      - name: Run Test
        run: yarn test

  # coverage:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up environment
  #       uses: ./.github/actions/setup
  #     - name: Run Coverage Checks
  #       run: yarn coverage

  audit:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - name: Set up environment
      # uses: ./.github/actions/setup
      - name: Audit packages for vulnerabilities
        run: yarn audit
