#Included:
#                 1. Install and Download Dependencies
#                 2. Compile Contracts
#                 3. Deploy a Contract to the Local network
#                 4. Test the locally deployed Contract in the local network.
#                 5. Run all tests
#                 6. slither integration

name: Contract Checks

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4

      - name: NPM install cache
        uses: c-hive/gha-npm-cache@v1

      - name: Install Node dependencies
        run: yarn install

      - name: Lint Contracts
        run: yarn lint:contracts
        continue-on-error: true

      - name: Compile & Build Contract
        run: yarn compile

      - name: Deploy Contracts
        run: yarn deploy

      - name: Interact With Contracts
        run: yarn interact

      - name: Run Test & Coverage
        run: |
          yarn test
          yarn coverage
