#Included:
#                 1. Install and Download Dependencies
#                 2. Compile Contracts
#                 3. Deploy a Contract to the Local network
#                 4. Test the locally deployed Contract in the local network.
#                 5. Run all tests
#                 6. slither integration

name: Contract Deployment

on: [push]

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  contract-ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile & Build Contracts
        run: yarn compile

      - name: Deploy Contracts Locally
        run: yarn deploy

      - name: Interact With Contracts
        run: yarn interact

      # - name: Run Coverage Checks
      #   run: yarn coverage
      #   continue-on-error: true
